---
- hosts: all
  gather_facts: false
  tasks:
  - name: Install Microsoft .NET Framework
  - name: Save the result of 'whoami' in 'whoami_out'
    win_command: whoami
    register: whoami_out

  - name: Run command that only runs if folder exists and runs from a specific folder
    win_command: wbadmin -backupTarget:C:\backup\
    args:
      chdir: C:\somedir\
      creates: C:\backup\
